### ISSUE TITLE
Fix scaling issue in landscape mode on tablet

### ISSUE THREAD

**Issue by a5-android** [vadiole/colorpicker#3]
Color Picker dialog is shown on a tablet (Samsung) device in landscape mode with 
 colorPicker.show(childFragmentManager, "color_picker")
Expected result: dialog is scaled to fit screen height (width of a screen, height of a media)
obtained result: color picker dialog not fit into media height, and no option to get access to dialog's view to scale programmatically.
See attached screenshot/
![device-2021-08-18-182045](https://user-images.githubusercontent.com/42936018/129926088-1fbda457-a359-488c-a604-a4bc3646ca49.png)

**Comment by vadiole** [comment]
@a5-android Hello!

fixed in version 1.0.3 #4
